# v1.3.14 February 6, 2014
# https://github.com/bevry/base
language: node_js
install: "npm install; ./node_modules/.bin/cake install"
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.8"
  - "0.10"
cache:
  directories:
    - node_modules
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
  email:
    recipients:
      - travisci@bevry.me
